#!/usr/bin/env php
<?php

use Geeks4change\BbndAnalyzer\Analyzer;
use Geeks4change\BbndAnalyzer\DebugAnalysisBuilder;

include 'vendor/autoload.php';

$fileId = $argv[1] ?? '';
$dir = dirname(__DIR__) . "/tests/examples";
$fileName = "$dir/$fileId.eml";
if (!file_exists($fileName)) {
  print("Possible examples:\n");
  foreach (glob("$dir/*.eml") as $fileName) {
    print basename($fileName, '.eml');
  }
  die(1);
}
$fileContent = file_get_contents($fileName);

$analyzer = new Analyzer();
$analysis = new DebugAnalysisBuilder();
$analyzer->analyze($analysis, $fileContent);
dump($analysis->getDebugOutput());
