#!/usr/bin/env php
<?php

use Geeks4change\BbndAnalyzer\Analyzer\Analyzer;

include 'vendor/autoload.php';

$fileId = $argv[1] ?? '';
$dir = dirname(__DIR__) . "/tests/examples";
$fileName = "$dir/$fileId.eml";
if (!file_exists($fileName)) {
  print("Runs an analysis on one of the packaged examples.\n");
  print("Possible examples:\n");
  foreach (glob("$dir/*.eml") as $fileName) {
    print basename($fileName, ".eml") . "\n";
  }
  die(1);
}
$fileContent = file_get_contents($fileName);

$analyzer = new Analyzer();
$result = $analyzer->analyze($fileContent);
// dump($result);
