#!/usr/bin/env php
<?php

use Geeks4change\BbndAnalyzer\Pattern\ToolPatternRepository;

include 'vendor/autoload.php';

$usage = "Usage: $argv[0] [service] [image|link] [pattern] [?string-to-match]\n";
[, $service, $typeName, $patternName, $string] = $argv + ['', '', '', '', ''];

$repo = new ToolPatternRepository();

/** @var \Geeks4change\BbndAnalyzer\Pattern\ToolPattern $toolPattern */
$toolPatternCollection = $repo->getToolPatternCollection();
$toolPattern = $toolPatternCollection[$service] ?? NULL;
if (!$toolPattern) {
  print $usage;
  printf("Available services: %s\n", implode('|', array_keys(iterator_to_array($toolPatternCollection))));
  exit(1);
}
/** @var \Geeks4change\BbndAnalyzer\Pattern\UrlPatternBase[] $types */
$types = [
  'link' => $toolPattern->getLinkPatterns(),
  'image' => $toolPattern->getImagePatterns(),
  'header' => $toolPattern->getHeaderPatterns(),
];
$patterns = $types[$typeName] ?? NULL;
if (!$patterns) {
  print $usage;
  printf("Available types: %s\n", implode('|', array_keys($types)));
  exit(1);
}
$pattern = $patterns[$patternName] ?? NULL;
if (!$pattern) {
  print $usage;
  /** @noinspection PhpParamsInspection */
  printf("Available patterns: %s\n", implode('|', array_keys($patterns)));
  exit(1);
}
$regex = $pattern->getRegex();
print "Pattern: $regex\n";
if ($string) {
  $match = $pattern->match($string);
  print "Match: ";
  print ($match ? 'Yes!' : 'nope');
  print "\n";
}
