#!/usr/bin/env php
<?php

use Geeks4change\UntrackEmailAnalyzer\Analyzer\Analyzer;
use Geeks4change\UntrackEmailAnalyzer\Api;
use Geeks4change\UntrackEmailAnalyzer\DirInfo;

include 'vendor/autoload.php';

$fileNamePairs = iterator_to_array(DirInfo::getTestEmailFileNames());
$fileId = $argv[1] ?? '';
if (!isset($fileNamePairs[$fileId])) {
  print("Print analysis report of on one of the packaged examples.\n");
  print("Possible examples:\n");
  $values = implode(' ', array_keys($fileNamePairs));
  print("Possible values: $values\n");
  die(1);
}
[$emailFile, $resultFile] = $fileNamePairs[$fileId];
$fileContent = file_get_contents($emailFile);

$analyzer = Api::getAnalyzer();
$result = $analyzer->analyze($fileContent);
$testSummary = $result->resultDetails->getTestSummary();
print $result->resultDetails->getAsPlainText();
