#!/usr/bin/env php
<?php

use Geeks4change\UntrackEmailAnalyzer\Analyzer\Analyzer;
use Symfony\Component\Yaml\Yaml;

include 'vendor/autoload.php';

$fileId = $argv[1] ?? '';
$dir = dirname(__DIR__) . "/tests/examples";
$fileName = "$dir/$fileId.eml";
if (!file_exists($fileName)) {
  print("Print test summary of on one of the packaged examples.\n");
  print("To refresh:\n");
  $patternsDir = 'tests/examples/foo.expected.yml';
  print("{$argv[0]} foo >$patternsDir\n");
  print("Possible examples:\n");
  foreach (glob("$dir/*.eml") as $fileName) {
    print basename($fileName, ".eml") . "\n";
  }
  die(1);
}
$fileContent = file_get_contents($fileName);

$analyzer = new Analyzer();
$result = $analyzer->analyze($fileContent);
$testSummary = $result->getReport()->getTestSummary();
print Yaml::dump($testSummary, 99);
