#!/usr/bin/env php
<?php

use Geeks4change\BbndAnalyzer\DomainAliases\DomainAliasesResolver;
use Geeks4change\BbndAnalyzer\DomElement\DomElementCollection;
use ZBateson\MailMimeParser\MailMimeParser;

include 'vendor/autoload.php';

if ($argc < 1) {
  print "Usage: urls [example]\n";
  die(1);
}

$fileId = $argv[1] ?? NULL;
$fileName = dirname(__DIR__) . "/tests/examples/$fileId.eml";
$emailWithHeaders = file_get_contents($fileName);

if (!$fileId || !$emailWithHeaders) {
  print("Need valid fileId");
  die(1);
}

$mailParser = new MailMimeParser();
$message = $mailParser->parse($emailWithHeaders, FALSE);
$html = $message->getHtmlContent();
$domainNameResolver = new DomainAliasesResolver();
$domElementCollection = DomElementCollection::fromHtml($html, $domainNameResolver);

/** @var \Geeks4change\BbndAnalyzer\DomElement\DomElementInterface $domElement */
foreach ($domElementCollection as $domElement) {
  print $domElement->getUrl()->getOriginalRelevantUrlPart() . "\n";
}
